### ISSUE TITLE
MetalKit support

### ISSUE THREAD

**Issue by adamnemecek** [gfx-rs/metal-rs#106]
I'm considering adding wrappers for MetalKit to this project. Is there any interest in this or not?

https://developer.apple.com/documentation/metalkit

**Comment by adamnemecek** [comment]
https://developer.apple.com/documentation/metalkit

**Comment by kvark** [comment]
@adamnemecek my feeling is that MetalKit is a higher level framework built on top of Metal itself, and thus on Rust side it should be a different wrapper crate that depends on metal-rs.

**Comment by adamnemecek** [comment]
Its the same level of abstraction. It just wraps some idioms into corresponding API.

Eg these unsafe lines of code are not needed https://github.com/gfx-rs/metal-rs/blob/master/examples/window/main.rs#L72

MTKView and MTKViewDelegate make using the framework a lot more pleasant.

**Comment by kvark** [comment]
I don't think this is correct, still.

Metal is the API that Apple platform implements by a combination of runtime + driver. Metal *Kit* is a wrapper library for working with Metal "quicker and easier, using far less code", it's a classical higher level abstraction thing. It's a library built on top of Metal: implementing new interfaces via the low-level ones, providing read-to-use shaders, etc.

The bindings to MetalKit should live in some `metal-toolkit-rs` library that doesn't exist yet.
@grovesNL please let us know if you feel differently.

**Comment by adamnemecek** [comment]
>  read-to-use shaders

You might be thinking about MetalPerformanceShaders, MetalKit doesn't provide ready-to-use shaders.

The main thing it provides is MTKView which frees you from the need to setup the layer and such yourself.  It's the recommended way of writing metal. 

Also, MTKViewDelegate is a much better way of rendering than alternatives.

**Comment by adamnemecek** [comment]
Ok, I create a crate, it's still WIP.


https://github.com/adamnemecek/metalkit

Do you happen to know how to wrap the MTKViewDelegate?

**Comment by kvark** [comment]
> You might be thinking about MetalPerformanceShaders, MetalKit doesn't provide ready-to-use shaders.

Indeed, thanks for correction!

> Also, MTKViewDelegate is a much better way of rendering than alternatives.

I don't question it's usefulness. What I'm saying is that it's built on top of Metal, it doesn't offer anything that you can't build manually on Metal.

> Ok, I create a crate, it's still WIP.

Great stuff! We'll happily follow, and this issue can now be closed.
