### ISSUE TITLE
Release 0.15.1

### ISSUE THREAD

**Issue by 0x6273** [gfx-rs/metal-rs#110]
0.15.0 currently does not compile (#109). This commit fixed that, but it is only in 0.16: https://github.com/gfx-rs/metal-rs/commit/032800fe731082ff115a5346b5178d12cfd1bf02

Would it be possible to get a 0.15.1 release with the aforementioned commit included? That way, crates that depend on 0.15, such as Amethyst, can compile without having to downgrade the objc crate.

**Comment by kvark** [comment]
Patches welcome! Latest metal-rs version in 0.17. What version of gfx-backend-metal does Amethyst use at the moment? Would it be possible for you to just do `cargo update -p gfx-backend-metal`, getting 0.4.2, which depends on metal-0.17?

**Comment by luojia65** [comment]
In my opinion newer version may use new `metal` dependency; but existing games with older version may still need a patch as 0.15.1 to compile without code change. (Random thoughts)

**Comment by kvark** [comment]
@luojia65 yes, we generally patch past releases, to some extent. We also accept patches to them. I was checking if the patch was necessary to begin with, which would be the case if Amethyst would update the dependency. I'll fix this shortly.

**Comment by kvark** [comment]
Done in https://crates.io/crates/metal/0.15.1
See the code in https://github.com/gfx-rs/metal-rs/tree/v0.15
