### ISSUE TITLE
Vsync?

### ISSUE THREAD

**Issue by rennis250** [gfx-rs/metal-rs#12]
According to the documentation on Apple's webpage, you can try to achieve vsync with the following command:

https://developer.apple.com/documentation/metal/mtlcommandbuffer/2806849-present

See here for some extra info:

https://developer.apple.com/library/content/documentation/3DDrawing/Conceptual/MTLBestPracticesGuide/FrameRate.html

However, changing

```rust
pub fn present_drawable<T>(&self, drawable: id<T>)
```

in commandbuffer.rs to take the additional afterMinimumDuration parameter, leads to a crash with the following error message:

```
2017-09-25 19:03:52.139 window[51292:591089] -[MTLIGAccelCommandBuffer presentDrawable:afterMinimumDuration:]: unrecognized selector sent to instance
```

Vsync is necessary for my work, so any ideas?

Unfortunately, I have no experience with Metal, Cocoa, AppKit, or the like, but willing to do whatever I can to help.

Best,
Rob

**Comment by kvark** [comment]
@JohnColanduoni and @fkaa are our main Metal experts, but they may not be fully responsive at this time.

From what I see in the [docs](https://developer.apple.com/documentation/metal/mtlcommandbuffer/2806849-presentdrawable?language=objc), the method variant with `afterMinimumDuration` parameter is only available on iOS 10.3 and tvOS 10.2. Are you trying to test it on a mac instead?

**Comment by rennis250** [comment]
Oh, I should have taken a closer look. Well, that's disappointing... Hmm... I'll do a bit more searching, but I suppose that I will have to accept that there may be no decent Vsync for Metal on macOS for the time being.

**Comment by kvark** [comment]
I'd look into SDL/glfw source code to see what they do.

**Comment by fkaa** [comment]
As far as i can recall VSync is on by default on macOS, at least when I was working with it.

**Comment by rennis250** [comment]
How did you measure it? I'm trying to finding the two best logical points to insert time measurements. For example, I've tried the following in the window example:

```rust
if let Some(drawable) = layer.next_drawable() {
   let s = time::precise_time_ns();
    ....
   let e = time::precise_time_ns();
   println!("{:?}", e - s);
}
```
Then I get the following values:
```
1879944
898908
349323
249012
428890
584386
927518
1285250
826689
974424
397832
766317
408452
1542721
440585
```
which are too small and too variable to be vsynced. They should all be around 16000000 at 60Hz.

**Comment by rennis250** [comment]
I took a look. Both GLFW’s and SDL’s vsync functionality is tied to OpenGL. I’m going to do a bit more searching.

**Comment by JohnColanduoni** [comment]
Internally CAMetalLayer uses CVDisplayLink when VSync is enabled (which like @fkaa said appears to be by default). That at least used to be how Apple recommended OpenGL applications drive their render loops (see [here](https://developer.apple.com/library/content/qa/qa1385/_index.html)) but that documentation is pretty outdated. It's possible you could get better results by registering a callback yourself and calling [present:atTime:](https://developer.apple.com/documentation/metal/mtlcommandbuffer/1442989-present), but I've never tried it.

**Comment by rennis250** [comment]
Thanks for that information. Doing a search for "CAMetalLayer CVDisplayLink" brought me to the following post, which seems to say that you need to explicitly ask for a CVDisplayLinkRef when working with Metal:

https://stackoverflow.com/questions/37794646/the-right-way-to-make-a-continuously-redrawn-metal-nsview

I'm going to try implementing this and see how it works.

Best,
Rob

**Comment by rennis250** [comment]
Wow, I just re-ran the example to see something and now it works. I didn't do anything with CVDisplayLink yet. I'm not sure what was going wrong before, although I wasn't getting too much sleep in the past days, so most likely an inability to remember where and how I was placing the ```time::precise_time_ns()``` statements...

Sorry about that! Thanks again for the help.

Best,
Rob

**Comment by rennis250** [comment]
Although, just as a warning, vsync precision has become more than 2x worse in High Sierra and is above the threshold for the line of work that I do, so that's unfortunate. Vsync precision was great in tests on Sierra, provided that one disabled a few of the fancy window animations and such things.

**Comment by JohnColanduoni** [comment]
@rennis250 High Sierra has added an explicit [`displaySyncEnabled`](https://developer.apple.com/documentation/quartzcore/cametallayer/2887087-displaysyncenabled) property. I've not played with it so I'm not sure if it's on by default but it may be worth a shot. [`allowNextDrawableTimeout`](https://developer.apple.com/documentation/quartzcore/cametallayer/2887086-allowsnextdrawabletimeout) might be related but there's no hint as to what they mean by that.

If you need high precision your best bet is probably to do an end-run around `CAMetalLayer` entirely. macOS (and newer iOS) have an API-independent handle to a GPU-resident texture called `IOSurface` that can be bound to a Metal texture. It's stable but almost entirely undocumented, however Chrome uses it and I've written a rough presentation system that uses it with Metal [here](https://github.com/gfx-rs/gfx/blob/ll/src/backend/metal/src/window.rs). Note that you'd still need to use `CVDisplayLink` to time the swapping of buffers (i.e. the `present` function in the code I linked).

**Comment by rennis250** [comment]
Interesting. Thanks a lot for this. When I again have some free time, I'll try it out. 👍
