### ISSUE TITLE
Is there any support for Vertex Amplification?

### ISSUE THREAD

**Issue by abd45** [gfx-rs/metal-rs#134]
Hi,
I am quite new to this repo. I was looking for Vertex Amplification support(https://developer.apple.com/documentation/metal/generating_multiple_output_vertex_streams_from_one_input_stream?language=objc) in the repo. But I have not found any. Am I missing something? Thank you.

**Comment by grovesNL** [comment]
Hi @abd45! This is a very recent feature (macOS 10.15.4+) so it's not exposed here yet, but we'd definitely be interested in supporting this.

Would you like to look into adding support for this to metal-rs and exposing all the necessary functions (e.g. https://developer.apple.com/documentation/metal/mtldevice/3197984-supportsvertexamplificationcount?language=objc)?

**Comment by abd45** [comment]
Hi @grovesNL
Yes, sure. I will be working on to add the support to metal-rs right away. Thank you very much.

**Comment by abd45** [comment]
Hi @grovesNL I raised a PR for this https://github.com/gfx-rs/metal-rs/pull/138 . Though I did some sanity check but would like to add an example for vertex amplification. Is there any unit test setup for metal-rs ?

**Comment by kvark** [comment]
There are no unit tests atm (would be nice to have them, but it's quite a bit of work!), only examples.

**Comment by abd45** [comment]
Hi @kvark , I am interested to start writing some unit test cases for this project. Let me know, if there is any blocker to do so. Thank you.

**Comment by abd45** [comment]
Closing this issue as the PR got merged.
