### ISSUE TITLE
MTLCaptureDescriptor

### ISSUE THREAD

**Issue by chinedufn** [gfx-rs/metal-rs#153]
Methods on the `MTLCaptureManager` such as `startCaptureWithDevice` are deprecated in `Metal` in favor of using an `MTLCaptureDescriptor`, which does not currently exist in `metal-rs`.

Example deprecation -> https://developer.apple.com/documentation/metal/mtlcapturemanager/2869714-startcapture

**Comment by chinedufn** [comment]
This is a blocker to #152 since there is currently no way to set the `.gpuTrace` output file since there is no capture descriptor.

**Comment by kvark** [comment]
Interesting! This is macOS 10.15 though, so we shouldn't remove the old stuff just yet.

**Comment by chinedufn** [comment]
Closed by #155
