### ISSUE TITLE
Remove core-graphics dependency

### ISSUE THREAD

**Issue by chinedufn** [gfx-rs/metal-rs#156]
Right now `core-graphics` is used on these two lines (excluding in examples. I'm talking strictly `metal-rs` source)

https://github.com/gfx-rs/metal-rs/blob/c17acf1aa38e05cf5fe293f6fc91e682ee71b2fb/src/lib.rs#L27-L28

Effectively we're using it to define type aliases for a couple of scalar types.

Given that the chances of these aliases ever changing is roughly 0%, I'm proposing that we ditch the `core-graphics` dependency and instead just copy-paste those two types inline in `metal-rs`.

The end result would be inlining the following code:

```rust
#[cfg(target_pointer_width = "64")]
type CGFloat = f64;
#[cfg(not(target_pointer_width = "64"))]
type CGFloat = f32;

#[repr(C)]
#[derive(Clone, Copy, Debug, Default, PartialEq)]
struct CGSize {
    pub width: CGFloat,
    pub height: CGFloat,
}
```

Am I missing anything here?

**Comment by kvark** [comment]
That sounds wonderful! I was wondering if it's going to be easy to do that as well.
