### ISSUE TITLE
Synchronizing events

### ISSUE THREAD

**Issue by mxpv** [gfx-rs/metal-rs#178]
Hello! Currently `metal-rs` provides no APIs to synchronize GPU/CPU work (like [MTLEvent](https://developer.apple.com/documentation/metal/mtlevent) and [MTLSharedEvent](https://developer.apple.com/documentation/metal/mtlsharedevent), example: [Synchronizing Events Within a Single Device](https://developer.apple.com/documentation/metal/synchronization/synchronizing_events_within_a_single_device)).
Would it be ok to open a PR to support that?

**Comment by kvark** [comment]
Yes, it would be great to have!
