### ISSUE TITLE
Publishing new version

### ISSUE THREAD

**Issue by aclysma** [gfx-rs/metal-rs#203]
I'm about ready to publish my crate but it requires some of the recent metal crate changes. Will a new version be published soon? Otherwise I'll need to publish a temporary fork like this one: https://crates.io/crates/cart-tmp-wgpu

**Comment by kvark** [comment]
We were waiting for #197, now we are all set.

**Comment by kvark** [comment]
https://crates.io/crates/metal/0.21.0
