### ISSUE TITLE
Different behaviour using Metal with Swift in Xcode vs Rust

### ISSUE THREAD

**Issue by andrewmilson** [gfx-rs/metal-rs#238]
I've noticed some different behaviour using Metal with Swift in Xcode vs this library with Rust.

1. Setting more than maximum threads per threadgroup to 1025 (max for my machine is 1024):
    * Rust: No error, program runs to finish
    * Swift: Errors with `-[MTLDebugComputeCommandEncoder _validateThreadsPerThreadgroup:]:946: failed assertion '(threadsPerThreadgroup.width(1025) * threadsPerThreadgroup.height(1) * threadsPerThreadgroup.depth(1))(1025) must be <= 1024. (device threadgroup size limit)'`
2. Passing an non page aligned pointer to `device.makeBuffer(bytesNoCopy:`
    * Rust (creating buffer with `device.new_buffer_with_bytes_no_copy`): Panics sometimes
    * Swift: Errors with `-[MTLDebugDevice newBufferWithBytesNoCopy:length:options:deallocator:]:687: failed assertion 'Buffer Validation
newBufferWithBytesNoCopy:pointer 0x12980a600 is not 4096 byte aligned.
'`
3. Accessing memory out of bounds in a compute kernel - I've got a command buffer with multiple compute kernels encoded into it
    * Rust: First encoded kernel executes. Remaining encoded kernels don't run. Rust code continues afterward un-alerted of the issue.
    * Swift: program crashes with `Program ended with exit code: 0`

**1.** and **2.** I notice are MTLDebug prefixed types which I assume Xcode must be using in debug mode. Looking online I couldn't find references to these types. **3.** I'm confused why the Swift program would crash but not Rust. I'm curious about why there is different behaviour here because these silent Metal failings in Rust have made for some tricky to track down bugs. Is it possible to enable the same set of debugging tools Xcode is running (for example using MTLDebug prefixed types in debug mode) when dealing with `metal-rs` in Rust?

**Comment by grovesNL** [comment]
Hi @andrewmilson! :wave:

The `MTLDebug` types are only added when you're using some special environment variables that Xcode is inserting. You can see these if you dump all of the environment variables when you run your Swift program. It's possible to crash inside the Metal debug wrappers if the validation catches issues or isn't supported by the debug wrappers.

It's described a little under https://github.com/gfx-rs/wgpu/wiki/Debugging-wgpu-Applications#metal (e.g. `METAL_DEVICE_WRAPPER_TYPE=1`) but there are some other variables besides that one. You might find some more info about these environment variables if you search around a bit, but in general there isn't great documentation about them. I've found it easiest to run a regular Metal application with Xcode and dump the environment variables.

**Comment by andrewmilson** [comment]
Hey @grovesNL 👋 . Thanks for that info. Super helpful.
