### ISSUE TITLE
Incorrect buffer value in compute example

### ISSUE THREAD

**Issue by WeiPhil** [gfx-rs/metal-rs#244]
Hi,
I was trying out some of the examples and it looks like the `compute` example only works for small vector sizes. To reproduce the issue simply replace the `let data = [1u32, 2, 3 , etc.. ];` to `let data = vec![1u32; 100000];` and assert that the sum should be 100000. In my case the value in the sum buffer is always the unmodified value 0. 
Can anyone explain to me what is happening here?
Best,
Philippe

**Comment by fornwall** [comment]
Having the number of elements being `16384` or bigger will cause the `compute` example to use a thread group size bigger than 1024:

```rust
let width = 16;

let thread_group_size = MTLSize {
    width: (NUM_ELEMENTS + width) / width,
    height: 1,
    depth: 1,
};
```

This is too big - see `Maximum threads per threadgroup` at https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf.

Running with `MTL_DEBUG_LAYER=1 cargo run --example compute` will indeed show the error:

> -[MTLDebugComputeCommandEncoder _validateThreadsPerThreadgroup:]:1027: failed assertion `(threadsPerThreadgroup.width(1025) * threadsPerThreadgroup.height(1) * threadsPerThreadgroup.depth(1))(1025) must be <= 1024. (device threadgroup size limit)'

**Comment by WeiPhil** [comment]
Awesome, thanks for the updated example as well!
