### ISSUE TITLE
Question about mesh shaders

### ISSUE THREAD

**Issue by taavetmaask** [gfx-rs/metal-rs#261]
Hi!

[Mesh shaders](https://developer.apple.com/videos/play/wwdc2022/10162/) have been out for Metal for some time now, is there any plan to add it to metal-rs as well?

**Comment by kvark** [comment]
I'm not aware of any work to add it, but it would be nice.

**Comment by taavetmaask** [comment]
Clear, thanks for the reply!

**Comment by rishflab** [comment]
https://github.com/gfx-rs/metal-rs/pull/264

Close this issue? 

It makes it look like metal-rs does not support mesh shader
