### ISSUE TITLE
Updating version on crates.io

### ISSUE THREAD

**Issue by andrewmilson** [gfx-rs/metal-rs#268]
Is it possible to update this crate on crates.io please? as the latest version is 11 months out of date.

I need some more recent features so I'm currently linking the library like so: `metal = { git = "https://github.com/gfx-rs/metal-rs" }`.  Although this is problematic as it's preventing me from publishing my own package to crates.io because "dependency `metal` does not specify a version". Thanks

**Comment by andrewmilson** [comment]
Hey @cwfitzgerald just following up on this please

**Comment by cwfitzgerald** [comment]
Thanks for the ping, version 0.25 released https://github.com/gfx-rs/metal-rs/releases/tag/v0.25.0
