### ISSUE TITLE
Need support to set dispatch type for `MTLComputePassDescriptor`

### ISSUE THREAD

**Issue by Snowapril** [gfx-rs/metal-rs#332]
Hi. I'm trying to optimize several compute pass gpu times in `wgpu` for practice.
But I found that there is no way to enable `MTLDispatchType::Concurrent` with `compute_command_encoder_with_descriptor`.

If there is no specific reason not to specify `MTLDispatchType` while using `MTLComputePassDescriptor`, I would like to support it.

**Comment by Snowapril** [comment]
Could I submit a pull-request for this? I already made a commit for this

**Comment by kvark** [comment]
Sorry for not responding to this earlier!
Generally, in a project like metal-rs, you could start a discussion with a PR right away.
Done in #335
