### ISSUE TITLE
Publish version 0.30.1

### ISSUE THREAD

**Issue by kvark** [gfx-rs/metal-rs#342]
I need the following PRs exposed on crates (to unblock blade-graphics):
- https://github.com/gfx-rs/metal-rs/pull/335
- https://github.com/gfx-rs/metal-rs/pull/336
- https://github.com/gfx-rs/metal-rs/pull/337

**Comment by cwfitzgerald** [comment]
There are breaking changes, so it'll need to be 0.31

**Comment by kvark** [comment]
Actually, I think we'd want to release everything except for `sample_buffer` changes (which is the only API breakage) as 0.30.1

**Comment by kvark** [comment]
@cwfitzgerald what is the replacement of metal-rs? I missed this transition.
I fixed the permissions in the Matrix, sorry for missing this originally!

**Comment by cwfitzgerald** [comment]
> what is the replacement of metal-rs?

[objc2-metal](https://docs.rs/objc2-metal/latest/objc2_metal/) as the mac ecosystem moves over from the abandoned objc crate to the objc2 family of crates, which are mostly autogenerated (iirc)
