### ISSUE TITLE
Fences and barriers?

### ISSUE THREAD

**Issue by swiftcoder** [gfx-rs/metal-rs#90]
I see that neither fences nor barriers are exposed by the rust API, and also I see that gfx-hal just uses a CPU sleep to emulate a fence.

Is that really equivalent to a GPU-side fence in metal, or am I missing something fundamental here?

**Comment by kvark** [comment]
Metal has [MTLFence](https://developer.apple.com/documentation/metal/mtlfence) that gfx-rs isn't using yet. It can't be used for CPU to wait for GPU, IIRC, it's more like a barrier thing in Metal for resources and heaps that are manually tracked.

**Comment by swiftcoder** [comment]
Makes sense. I'd glossed over the fact that managed resources don't need barriers since the runtime manages it automatically.

**Comment by kvark** [comment]
FYI, manually tracking resources and using Vulkan barriers on Metal is something we want to do at some point (any help is appreciated!).
